INSERT INTO app_role
("name", permissions, "locked", active, archive, created_on, updated_on, created_by, updated_by)
VALUES('Admin', '[{"resource":"site","path":["/secure/dashboard","/secure/profile"]},{"resource":"roles","path":"/secure/roles","policies":[{"action":"read","path":"","properties":["name","permissions"]},{"action":"add","path":"/new","properties":["name","permissions"]},{"action":"edit","path":"/edit","properties":["name","permissions"]},{"action":"delete"}]},{"resource":"users","path":"/secure/users","policies":[{"action":"read","path":"","properties":["fullname","email","phone","location"]},{"action":"add","path":"/new","properties":["fullname","email","phone","location","role","password"]},{"action":"edit","path":"/edit","properties":["fullname","email","phone","location","role"]},{"action":"delete"}]},{"resource":"products","path":"/secure/products","policies":[{"action":"read","path":"/list","properties":["title","description"]},{"action":"add","path":"/new","properties":["title","description"]},{"action":"edit","path":"/edit","properties":["title"]},{"action":"delete"}]},{"resource":"vendors","path":"/secure/vendors","policies":[{"action":"read","path":"/list","properties":["name"]},{"action":"add","path":"/new","properties":["name"]},{"action":"edit","path":"/edit","properties":["name"]},{"action":"delete"}]},{"resource":"purchases","path":"/secure/purchases","policies":[{"action":"read","path":"/list","properties":["name"]},{"action":"add","path":"/new","properties":["name"]},{"action":"edit","path":"/edit","properties":["name"]},{"action":"delete"}]},{"resource":"stock","path":"/secure/purchases/stock","policies":[{"action":"read","properties":["ptrcost"]}]},{"resource":"customers","path":"/secure/customers","policies":[{"action":"read","properties":[]}]},{"resource":"sales","path":"/secure/sales","data":"all","policies":[{"action":"read","properties":[]},{"action":"view","properties":[]},{"action":"add","path":"/new","properties":[]},{"action":"bill","path":"/bill/print"}]}]', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0);

INSERT INTO app_role
("name", permissions, "locked", active, archive, created_on, updated_on, created_by, updated_by)
VALUES('User', '[{"resource":"site","path":["/secure/dashboard","/secure/profile"]},{"resource":"sales","path":"/secure/sales","policies":[{"action":"read","properties":[]},{"action":"add","path":"/new","properties":[]}]}]', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0);

insert into vendor (business_name) values ('Karthikeyan Drug House');
insert into vendor (business_name) values ('Seyon Pharmaceuticals');
insert into vendor (business_name) values ('Marudhars');
insert into vendor (business_name) values ('Evergreen Pharma');
insert into vendor (business_name) values ('Lehar Pharma');

insert into customer ("name",mobile) values ('Anonymous','00000');