FROM node:16.19.0
# Create a Virtual directory inside the docker image
WORKDIR /dist/src/app

# Copy files from local machine to virtual directory in docker image
COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 4200