FROM node:16.19.0 as build
# # Create a Virtual directory inside the docker image
WORKDIR /app

# # Copy files from local machine to virtual directory in docker image
COPY package*.json ./

RUN npm install --legacy-peer-deps

RUN npm install -g @angular/cli@12.0.0

COPY . .

ARG API_URL=http://localhost:3000
RUN sed -i "s|API_URL_PLACEHOLDER|${API_URL}|g" src/environments/environment.prod.ts

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist/frontend /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
