version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile.prod
      context: ./api
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules
      - rgpfiles:/app/uploaded-files
    command: npm run start:prod
    depends_on:
      - postgres
    ports:
      - 30001:3001
    networks:  
      - local

  postgres:
    image: postgres:14
    restart: always
    container_name: rgp-db
    volumes:
      - rgpdata:/var/lib/postgresql/data
    networks:  
      - local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rgpdb
    ports:
      - 35000:5432
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   container_name: pgadmin
  #   networks:  
  #     - local
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@rgp.com
  #     PGADMIN_DEFAULT_PASSWORD: R6PD8@dmin
  #   ports:
  #     - 9080:80

  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend
    depends_on:
      - api
    volumes:
      - ./dist/frontend:/usr/share/nginx/html
    ports:
      - 8080:80
    networks:  
      - local

networks:
  local:

volumes:
    rgpdata:
      external: true
    rgpfiles:
      external: true