export interface Invoice {
    id?:number,
    invoiceno?:string,
    grno?:string,
    invoicedate?:string,
    duedate?:string,
    vendorid?:number,
    purchaseorderid?:number,
    vendor?:any,
    status?:string,
    paymentstatus?:string,
    total?:number,
    paidamount?:number,
    balanceamount?:number,
    referenceno?:string,
    notes?:string,
    items?:any[],
    payments?:any[]
}
