TRUNCATE TABLE public.app_role RESTART IDENTITY CASCADE;

INSERT INTO public.app_role
(id, "name", permissions, "locked", active, archive)
VALUES
(4, 'Site Admin', '[{"resource":"site","path":["/secure/dashboard","/secure/profile","/secure/settings/businesses","/secure/settings/users"]},{"resource":"businesses","path":"/secure/settings/businesses","policies":[{"action":"manage"},{"action":"read"},{"action":"add"},{"action":"edit"},{"action":"delete"}]},{"resource":"roles","path":"/secure/settings/roles","policies":[{"action":"read","path":"","properties":["name","permissions"]},{"action":"add","path":"/new","properties":["name","permissions"]},{"action":"edit","path":"/edit","properties":["name","permissions"]},{"action":"delete"}]},{"resource":"users","path":"/secure/settings/users","policies":[{"action":"read","path":"","properties":["fullname","email","phone","location"]},{"action":"add","path":"/new","properties":["fullname","email","phone","location","password","businessid"]},{"action":"edit","path":"/edit","properties":["fullname","email","phone","location","businessid"]},{"action":"delete"}]},{"resource":"settings","path":["/secure/settings/businesses","/secure/settings/users","/secure/settings/roles"],"data":"all","policies":[{"action":"read","properties":[]},{"action":"view","properties":[]},{"action":"add","path":"/new","properties":[]}]}]'::json, true, true, false),
(1, 'Business Head', '[{"resource":"site","path":["/secure/settings/users","/secure/settings/store","/secure/dashboard","/secure/profile"]},{"resource":"roles","path":"/secure/settings/roles","policies":[{"action":"read","path":"","properties":["name","permissions"]},{"action":"add","path":"/new","properties":["name","permissions"]},{"action":"edit","path":"/edit","properties":["name","permissions"]},{"action":"delete"}]},{"resource":"users","path":"/secure/settings/users","policies":[{"action":"read","path":"","properties":["fullname","email","phone","location"]},{"action":"add","path":"/new","properties":["fullname","email","phone","location","role","password","storeids"]},{"action":"edit","path":"/edit","properties":["fullname","email","phone","location","role","storeids"]},{"action":"delete"}]},{"resource":"storesettings","path":"/secure/settings/store","policies":[{"action":"read"},{"action":"add"},{"action":"edit"},{"action":"delete"}]},{"resource":"products","path":"/secure/products","policies":[{"action":"price","path":"/price","properties":["title","description"]},{"action":"add","path":"/new","properties":["title","description"]},{"action":"edit","path":"/edit","properties":["title"]},{"action":"delete"}]},{"resource":"purchases","path":["/secure/purchases","/secure/purchases/vendors","/secure/settings/delivery-partners"],"policies":[{"action":"read","path":"/list","properties":["name"]},{"action":"add","path":"/new","properties":["name"]},{"action":"edit","path":"/edit","properties":["name"]},{"action":"vendors.edit","path":"vendors/edit","properties":["name"]},{"action":"delete"}]},{"resource":"purchaseorders","path":["/secure/purchases/orders"],"policies":[{"action":"approve"},{"action":"reject"}]},{"resource":"store","path":["/secure/store/stock","/secure/store/cash","/secure/store/shifts"],"policies":[{"action":"read","properties":["ptrcost"]},{"action":"adjust"}]},{"resource":"customers","path":"/secure/customers","policies":[{"action":"read","properties":[]}]},{"resource":"sales","path":["/secure/sales/pos","/secure/sales/pos/new","/secure/sales/list","/secure/sales/view","/secure/sales/new","/secure/sales/edit","/secure/sales/returns","/secure/sales/reminders","/secure/sales/deliveries"],"data":"all","policies":[{"action":"read","properties":[]},{"action":"view","properties":[]},{"action":"add","path":"/new","properties":[]},{"action":"bill","path":"/bill/print"}]},{"resource":"settings","path":["/secure/settings/users","/secure/settings/roles","/secure/settings/store"],"data":"all","policies":[{"action":"read","properties":[]},{"action":"view","properties":[]},{"action":"add","path":"/new","properties":[]}]},{"resource":"reports","path":["/secure/reports"]}]'::json, false, true, false),
(2, 'Sales Staff', '[{"resource":"site","path":["/secure/sales","/secure/profile"]},{"resource":"stock","path":"/secure/stock","policies":[{"action":"read","properties":[]}]},{"resource":"customers","path":"/secure/customers","policies":[{"action":"read","properties":[]}]},{"resource":"sales","path":"/secure/sales","policies":[{"action":"read","properties":[]},{"action":"add","path":"/new","properties":[]}]},{"resource":"purchases","path":"/secure/purchases","policies":[{"action":"read","path":"/list","properties":[]}]}]'::json, false, true, false),
(3, 'Store Head', '[{"resource":"site","path":["/secure/dashboard","/secure/profile"]},{"resource":"products","path":"/secure/products","policies":[{"action":"price","path":"/price","properties":["title","description"]},{"action":"add","path":"/new","properties":["title","description"]},{"action":"edit","path":"/edit","properties":["title"]},{"action":"delete"}]},{"resource":"purchases","path":["/secure/purchases","/secure/purchases/vendors","/secure/settings/delivery-partners"],"policies":[{"action":"read","path":"/list","properties":["name"]},{"action":"add","path":"/new","properties":["name"]},{"action":"edit","path":"/edit","properties":["name"]},{"action":"vendors.edit","path":"vendors/edit","properties":["name"]},{"action":"delete"}]},{"resource":"purchaseorders","path":"/secure/purchases/orders","policies":[{"action":"approve"},{"action":"reject"}]},{"resource":"store","path":["/secure/store/stock","/secure/store/cash","/secure/store/shifts"],"policies":[{"action":"read","properties":["ptrcost"]},{"action":"adjust"}]},{"resource":"customers","path":"/secure/customers","policies":[{"action":"read","properties":[]}]},{"resource":"sales","path":["/secure/sales/pos","/secure/sales/pos/new","/secure/sales/list","/secure/sales/view","/secure/sales/new","/secure/sales/edit","/secure/sales/returns","/secure/sales/reminders"],"data":"all","policies":[{"action":"read","properties":[]},{"action":"view","properties":[]},{"action":"add","path":"/new","properties":[]},{"action":"bill","path":"/bill/print"}]},{"resource":"reports","path":["/secure/reports"]}]'::json, false, true, false)
ON CONFLICT (id) DO UPDATE
SET
    "name" = EXCLUDED."name",
    permissions = EXCLUDED.permissions,
    "locked" = EXCLUDED."locked",
    active = EXCLUDED.active,
    archive = EXCLUDED.archive;

INSERT INTO public.app_setting
(category, setting_key, setting_value, description, active, archive, created_by, updated_by)
VALUES
('purchases', 'purchase_order_approval_value_threshold', '5000', 'Approval required above this estimated PO value', true, false, 1, 1)
ON CONFLICT (setting_key) DO UPDATE
SET
    setting_value = EXCLUDED.setting_value,
    description = EXCLUDED.description,
    active = EXCLUDED.active,
    archive = EXCLUDED.archive,
    updated_by = EXCLUDED.updated_by,
    updated_on = CURRENT_TIMESTAMP;
