export interface SaleDelivery {
    id?: number,
    saleid?: number,
    sale?: any,
    saleperson?: string,
    bookeddate?: string,
    bookedby?: number,
    receivername?: string,
    receiverphone?: string,
    receiveraddress?: string,
    charges?: number,
    actualcost?: number,
    deliverydate?: string,
    deliveryby?: string,
    deliverymethod?: string,
    courierpartner?: string,
    deliveredat?: string,
    confirmed?: boolean,
    confirmedby?: string,
    confirmedat?: string,
    paymentmode?: string,
    collectionstatus?: string,
    failurereason?: string,
    status?: string,
    comments?: string
}
